modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
    modId="explorationexperience"
    version="1.0"
    logoFile="logo.png"
    displayName="Exploration Experience"
    authors="BlackGear"
    description='''no description'''

[[dependencies.explorationexperience]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.72,)"
    ordering="NONE"

[[dependencies.explorationexperience]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.explorationexperience]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.2,)"
    ordering="AFTER"
    side="BOTH"
