package com.blackgear.explorationexperience.core.registries.common;

import com.blackgear.explorationexperience.core.ExplorationExperience;
import com.teamabnormals.abnormals_core.common.blocks.wood.AbnormalsLogBlock;
import com.teamabnormals.abnormals_core.common.blocks.wood.PlanksBlock;
import com.teamabnormals.abnormals_core.common.blocks.wood.StrippedLogBlock;
import com.teamabnormals.abnormals_core.common.blocks.wood.StrippedWoodBlock;
import com.teamabnormals.abnormals_core.common.blocks.wood.WoodBlock;
import com.teamabnormals.abnormals_core.common.blocks.wood.WoodSlabBlock;
import com.teamabnormals.abnormals_core.common.blocks.wood.WoodStairsBlock;
import com.teamabnormals.abnormals_core.core.utils.RegistryHelper;

import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.FenceBlock;
import net.minecraft.block.SoundType;
import net.minecraft.block.TrapDoorBlock;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.item.ItemGroup;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.fml.common.Mod;

//<>

@Mod.EventBusSubscriber(modid = ExplorationExperience.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class EEBlocks {
	public static final RegistryHelper HELPER = ExplorationExperience.REGISTRY_HELPER;
	
	//BUILDING BLOCKS
	
	public static final RegistryObject<Block> MUSHROOM_STEM 						= HELPER.createBlock("mushroom_stem", () -> new AbnormalsLogBlock(() -> EEBlocks.STRIPPED_MUSHROOM_STEM.get(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOL).hardnessAndResistance(2.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> STRIPPED_MUSHROOM_STEM 	= HELPER.createBlock("stripped_mushroom_stem", () -> new StrippedLogBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOL).hardnessAndResistance(2.0f).sound(SoundType.WOOD)) ,ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> MUSHROOM_HYPHAE 				= HELPER.createBlock("mushroom_hyphae", () -> new WoodBlock(() -> EEBlocks.STRIPPED_MUSHROOM_HYPHAE.get(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOL).hardnessAndResistance(2.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> STRIPPED_MUSHROOM_HYPHAE 		= HELPER.createBlock("stripped_mushroom_hyphae", () -> new StrippedWoodBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOL).hardnessAndResistance(2.0f).sound(SoundType.WOOD)) ,ItemGroup.BUILDING_BLOCKS);	
	
	public static final RegistryObject<Block> FUNGAL_PLANKS 				= HELPER.createBlock("fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOL).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> WHITE_FUNGAL_PLANKS 			= HELPER.createBlock("white_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.SNOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> ORANGE_FUNGAL_PLANKS 			= HELPER.createBlock("orange_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.ADOBE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> MAGENTA_FUNGAL_PLANKS 		= HELPER.createBlock("magenta_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.MAGENTA).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> LIGHT_BLUE_FUNGAL_PLANKS 		= HELPER.createBlock("light_blue_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> YELLOW_FUNGAL_PLANKS 			= HELPER.createBlock("yellow_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.YELLOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> LIME_FUNGAL_PLANKS 			= HELPER.createBlock("lime_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIME).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> PINK_FUNGAL_PLANKS 			= HELPER.createBlock("pink_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PINK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> GRAY_FUNGAL_PLANKS 			= HELPER.createBlock("gray_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> LIGHT_GRAY_FUNGAL_PLANKS 		= HELPER.createBlock("light_gray_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> CYAN_FUNGAL_PLANKS 			= HELPER.createBlock("cyan_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.CYAN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> PURPLE_FUNGAL_PLANKS 			= HELPER.createBlock("purple_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PURPLE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> BLUE_FUNGAL_PLANKS 			= HELPER.createBlock("blue_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> BROWN_FUNGAL_PLANKS 			= HELPER.createBlock("brown_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BROWN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> GREEN_FUNGAL_PLANKS 			= HELPER.createBlock("green_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GREEN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> RED_FUNGAL_PLANKS 			= HELPER.createBlock("red_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.RED).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> BLACK_FUNGAL_PLANKS 			= HELPER.createBlock("black_fungal_planks", () -> new PlanksBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLACK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	
	public static final RegistryObject<Block> FUNGAL_STAIRS 				= HELPER.createBlock("fungal_stairs", () -> new WoodStairsBlock(EEBlocks.FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOL).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> WHITE_FUNGAL_STAIRS 			= HELPER.createBlock("white_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.WHITE_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.SNOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> ORANGE_FUNGAL_STAIRS 			= HELPER.createBlock("orange_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.ORANGE_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.ADOBE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> MAGENTA_FUNGAL_STAIRS 		= HELPER.createBlock("magenta_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.MAGENTA_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.MAGENTA).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> LIGHT_BLUE_FUNGAL_STAIRS		= HELPER.createBlock("light_blue_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.LIGHT_BLUE_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> YELLOW_FUNGAL_STAIRS 			= HELPER.createBlock("yellow_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.YELLOW_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.YELLOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> LIME_FUNGAL_STAIRS			= HELPER.createBlock("lime_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.LIME_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIME).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> PINK_FUNGAL_STAIRS 			= HELPER.createBlock("pink_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.PINK_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PINK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> GRAY_FUNGAL_STAIRS 			= HELPER.createBlock("gray_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.GRAY_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> LIGHT_GRAY_FUNGAL_STAIRS		= HELPER.createBlock("light_gray_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.LIGHT_GRAY_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> CYAN_FUNGAL_STAIRS			= HELPER.createBlock("cyan_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.CYAN_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.CYAN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> PURPLE_FUNGAL_STAIRS			= HELPER.createBlock("purple_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.PURPLE_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PURPLE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> BLUE_FUNGAL_STAIRS 			= HELPER.createBlock("blue_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.BLUE_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> BROWN_FUNGAL_STAIRS 			= HELPER.createBlock("brown_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.BROWN_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BROWN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> GREEN_FUNGAL_STAIRS 			= HELPER.createBlock("green_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.GREEN_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GREEN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> RED_FUNGAL_STAIRS 			= HELPER.createBlock("red_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.RED_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.RED).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> BLACK_FUNGAL_STAIRS 			= HELPER.createBlock("black_fungal_stairs", () -> new WoodStairsBlock(EEBlocks.BLACK_FUNGAL_PLANKS.get().getDefaultState(), AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLACK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	
	public static final RegistryObject<Block> FUNGAL_SLAB	 				= HELPER.createBlock("fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOL).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> WHITE_FUNGAL_SLAB 			= HELPER.createBlock("white_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.SNOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> ORANGE_FUNGAL_SLAB 			= HELPER.createBlock("orange_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.ADOBE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> MAGENTA_FUNGAL_SLAB 			= HELPER.createBlock("magenta_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.MAGENTA).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> LIGHT_BLUE_FUNGAL_SLAB		= HELPER.createBlock("light_blue_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> YELLOW_FUNGAL_SLAB 			= HELPER.createBlock("yellow_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.YELLOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> LIME_FUNGAL_SLAB				= HELPER.createBlock("lime_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIME).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> PINK_FUNGAL_SLAB 				= HELPER.createBlock("pink_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PINK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> GRAY_FUNGAL_SLAB 				= HELPER.createBlock("gray_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> LIGHT_GRAY_FUNGAL_SLAB		= HELPER.createBlock("light_gray_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> CYAN_FUNGAL_SLAB				= HELPER.createBlock("cyan_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.CYAN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> PURPLE_FUNGAL_SLAB			= HELPER.createBlock("purple_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PURPLE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> BLUE_FUNGAL_SLAB 				= HELPER.createBlock("blue_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> BROWN_FUNGAL_SLAB 			= HELPER.createBlock("brown_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BROWN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> GREEN_FUNGAL_SLAB 			= HELPER.createBlock("green_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GREEN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> RED_FUNGAL_SLAB 				= HELPER.createBlock("red_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.RED).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	public static final RegistryObject<Block> BLACK_FUNGAL_SLAB 			= HELPER.createBlock("black_fungal_slab", () -> new WoodSlabBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLACK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.BUILDING_BLOCKS);
	
	// DECORATION BLOCKS
	
	public static final RegistryObject<Block> FUNGAL_FENCE 					= HELPER.createBlock("fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOL).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> WHITE_FUNGAL_FENCE			= HELPER.createBlock("white_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.SNOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> ORANGE_FUNGAL_FENCE 			= HELPER.createBlock("orange_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.ADOBE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> MAGENTA_FUNGAL_FENCE 			= HELPER.createBlock("magenta_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.MAGENTA).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> LIGHT_BLUE_FUNGAL_FENCE 		= HELPER.createBlock("light_blue_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> YELLOW_FUNGAL_FENCE 			= HELPER.createBlock("yellow_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.YELLOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> LIME_FUNGAL_FENCE 			= HELPER.createBlock("lime_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIME).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> PINK_FUNGAL_FENCE 			= HELPER.createBlock("pink_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PINK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> GRAY_FUNGAL_FENCE 			= HELPER.createBlock("gray_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> LIGHT_GRAY_FUNGAL_FENCE 		= HELPER.createBlock("light_gray_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> CYAN_FUNGAL_FENCE 			= HELPER.createBlock("cyan_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.CYAN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> PURPLE_FUNGAL_FENCE 			= HELPER.createBlock("purple_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PURPLE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> BLUE_FUNGAL_FENCE 							= HELPER.createBlock("blue_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> BROWN_FUNGAL_FENCE 						= HELPER.createBlock("brown_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BROWN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> GREEN_FUNGAL_FENCE 							= HELPER.createBlock("green_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GREEN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> RED_FUNGAL_FENCE 								= HELPER.createBlock("red_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.RED).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	public static final RegistryObject<Block> BLACK_FUNGAL_FENCE 							= HELPER.createBlock("black_fungal_fence", () -> new FenceBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLACK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.DECORATIONS);
	
	// REDSTONE BLOCKS
	
	public static final RegistryObject<Block> FUNGAL_TRAPDOOR 								= HELPER.createBlock("fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOL).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> WHITE_FUNGAL_TRAPDOOR					= HELPER.createBlock("white_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.SNOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> ORANGE_FUNGAL_TRAPDOOR 			= HELPER.createBlock("orange_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.ADOBE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> MAGENTA_FUNGAL_TRAPDOOR 			= HELPER.createBlock("magenta_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.MAGENTA).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> LIGHT_BLUE_FUNGAL_TRAPDOOR 		= HELPER.createBlock("light_blue_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> YELLOW_FUNGAL_TRAPDOOR 				= HELPER.createBlock("yellow_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.YELLOW).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> LIME_FUNGAL_TRAPDOOR 					= HELPER.createBlock("lime_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIME).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> PINK_FUNGAL_TRAPDOOR 					= HELPER.createBlock("pink_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PINK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> GRAY_FUNGAL_TRAPDOOR 					= HELPER.createBlock("gray_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> LIGHT_GRAY_FUNGAL_TRAPDOOR 		= HELPER.createBlock("light_gray_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.LIGHT_GRAY).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> CYAN_FUNGAL_TRAPDOOR 					= HELPER.createBlock("cyan_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.CYAN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> PURPLE_FUNGAL_TRAPDOOR 				= HELPER.createBlock("purple_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.PURPLE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> BLUE_FUNGAL_TRAPDOOR 					= HELPER.createBlock("blue_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLUE).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> BROWN_FUNGAL_TRAPDOOR 				= HELPER.createBlock("brown_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BROWN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> GREEN_FUNGAL_TRAPDOOR 				= HELPER.createBlock("green_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.GREEN).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> RED_FUNGAL_TRAPDOOR 						= HELPER.createBlock("red_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.RED).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
	public static final RegistryObject<Block> BLACK_FUNGAL_TRAPDOOR 				= HELPER.createBlock("black_fungal_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.BLACK).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), ItemGroup.REDSTONE);
}